name: p100
groups:
  - name: premium
    weight: 1
    slo_lower:
      tier_0: 0
      tier_1: 0
      tier_2: 0
      tier_3: 0
      tier_4: 1
    slo_upper:
      tier_0: 0
      tier_1: 0
      tier_2: 0
      tier_3: 0
      tier_4: 1
