name: p95
groups:
  - name: best-effort
    weight: 0.05
    slo_lower:
      bad: 1
      good: 0
    slo_upper:
      bad: 0
      good: 1
  - name: premium
    weight: 0.95
    slo_lower:
      bad: 0
      good: 1
    slo_upper:
      bad: 0
      good: 1
