defaults:
  - _self_
  - optimizer: qt
  - user_groups: p0

seed: 0
qor_target: 0.5

requests_dataset: wiki_en
region: CISO

vp: 24  # validity period duration

model_qualities:
  - tier_0
  - tier_1
  - tier_2
  - tier_3
  - tier_4

machines:
  - _target_: src.scenario.Machine
    name: AWS_p4d.24xlarge
    power_usage: 3.7818
    pue: 1
    performance:
      tier_0: 42000
      tier_1: 32000
      tier_2: 25000
      tier_3: 20000
      tier_4: 15000
    embedded_carbon: 135
  - _target_: src.scenario.Machine
    name: AWS_p5.48xlarge
    power_usage: 4.4
    pue: 1
    performance:
      tier_0: 52000
      tier_1: 41000
      tier_2: 33000
      tier_3: 27000
      tier_4: 21000
    embedded_carbon: 150
  - _target_: src.scenario.Machine
    name: AWS_p6-b200.48xlarge
    power_usage: 5.2
    pue: 1
    performance:
      tier_0: 63000
      tier_1: 52000
      tier_2: 43000
      tier_3: 34000
      tier_4: 25000
    embedded_carbon: 165

result_dir: results
